# Generated by Django 5.1 on 2024-08-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cool_todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
    ]
